### PR TITLE
implement watch

### PR DESCRIPTION
**Pull request by EasonLiao**
i'm planning on writing some integration tests (start 3 servers, send requests, verify results), and i need to be able to wait for files/directories to become certain versions.
# 

Wait for a file to get created. This returns immediately if the file already exists.

```
GET /file?wait=0 HTTP/1.1
```

Wait until the file version is at least 1. This returns immediately if the file version is already greater than or equal to 1. This also returns if the file doesn't exist, or it gets deleted before reaching version 1.

```
GET /file?wait=1 HTTP/1.1
```

Wait until the file gets deleted. This returns immediately if the file does not exist.

```
GET /file?wait=-1 HTTP/1.1
```

### CODE REVIEW

**Comment by EasonLiao** [comment]
@m1ch1  one question : 

> GET /file?wait=0 HTTP/1.1
> Wait for a file to get created. This returns immediately if the file already exists.

Do we need to support this? I guess ZooKeeper doesn't support this kind of watch.  I'm asking this question because I think this is not necessary and it will add complexities to implementation. Since for other watches we can store them in Node class, but for this watch we can't because it's watching something which don't exist.

**Comment by ghost** [comment]
zookeeper does support watching for znode creation:

http://zookeeper.apache.org/doc/trunk/zookeeperProgrammers.html#ch_zkWatches

**Comment by EasonLiao** [comment]
It's not ready for review yet.

**Comment by EasonLiao** [comment]
@m1ch1  it's ready for review now.

**Comment by EasonLiao** [comment]
Because for each update we'll bump the version all the way to the root node, so for each update we need to check the possibility of triggering the watches for all nodes along the path. And the problem is that when do we want to trigger the watches, we can't trigger them during the recursion since during the recursion it can fail(throw exceptions) anytime during the call and even in future we'll need to support batch requests (all or nothing), so we can only trigger the watches when we do atomic swap of the root node.

**Comment by EasonLiao** [comment]
Another problem is where should we process wait request, we could handle them in `doGet` function because it doesn't need to be broadcasted, but the problem is we need to deal with concurrent `doGet` call and at the same time deliver thread can modify the tree, so we need have synchronization/lock if we done in this way.

Instead I make wait request to be a WatchCommand and make it a flush request, since there's a single thread process both flushed and delivered requests, we don't need lock/synchronization at all.

**Comment by ghost** [comment]
it would be nice if we can handle watches locally without flushing. i just
merged the pull request, but let's have a separate issue and think about
whether we can avoid flushing.

https://github.com/zk1931/pulsed/issues/25

**Comment by ghost** [comment]
right, that makes sense.

**Pull request merged**
