### PR TITLE
wait should return if file/directory gets deleted before reaching the version

### PR DESCRIPTION
**Pull request by EasonLiao**
say you did "GET /file?wait=100" but /file gets deleted before reaching version 100. in this case we should return 404. this is consistent with GET /file?wait=100 returning 404 if /file doesn't exist.

### CODE REVIEW

**Comment by ghost** [comment]
sorry right now GET /file?wait=100 doesn't return 404 if the file doesn't exist, but i think we should :)

watch should return if the file gets deleted so that the client knows if the file gets deleted before reaching the version. otherwise the client ends up watching a different file with a same name.

**Comment by EasonLiao** [comment]
Probably we should  finish a complete spec first

**Comment by ghost** [comment]
will do

**Comment by ghost** [comment]
https://github.com/zk1931/pulsed/pull/52

**Comment by EasonLiao** [comment]
@m1ch1

**Comment by EasonLiao** [comment]
also fixed the travis build error

**Pull request merged**
