### PR TITLE
Does PUT/DELETE with version check.

### PR DESCRIPTION
**Pull request by EasonLiao**
- If version is -1 in PUT, then treat is as creation.
- If version > -1 in PUT, then treat is as set.
- If version > -1 in DELETE, then delete node if and only if versions
  match.

### CODE REVIEW

**Comment by ghost** [comment]
typos in commit messages: is => it

**Comment by EasonLiao** [comment]
Sure, will do

**Comment by ghost** [comment]
also, the commit message is somewhat confusing. it says:

```
- If version > -1 in PUT, then treat is as set.
- If version > -1 in DELETE, then delete node if and only if versions match.
```

this makes it look like there is not version check for PUT requests.

**Comment by EasonLiao** [comment]
@m1ch1

**Comment by EasonLiao** [comment]
@m1ch1

**Comment by ghost** [comment]
https://travis-ci.org/zk1931/pulsed/jobs/43403767

There is an apparent infinite recursive loop in com.github.zk1931.pulsed.Utils.replyConflict(HttpServletResponse, String) ["com.github.zk1931.pulsed.Utils"] At Utils.java:[lines 39-243]

**Comment by EasonLiao** [comment]
Yes, I'll fix this in next PR

**Pull request merged**
