### PR TITLE
List children recursively

### PR DESCRIPTION
**Pull request by EasonLiao**
e.g.

GET /?recursive HTTP/1.1

HTTP/1.1 200 OK
Date: Wed, 03 Dec 2014 19:54:39 GMT
version: 6
type: directory
path: /
Content-Length: 942
Server: Jetty(9.2.z-SNAPSHOT)

{
  "session": -1,
  "path": "/",
  "children": [
    {
      "session": -1,
      "path": "/dir",
      "children": [
        {
          "session": -1,
          "path": "/dir/0000000000000000000",
          "type": "file",
          "version": "0"
        },
        {
          "session": -1,
          "path": "/dir/0000000000000000001",
          "type": "file",
          "version": "0"
        },
        {
          "session": -1,
          "path": "/dir/0000000000000000002",
          "type": "file",
          "version": "0"
        },
        {
          "session": -1,
          "path": "/dir/0000000000000000003",
          "type": "file",
          "version": "0"
        },
        {
          "session": -1,
          "path": "/dir/0000000000000000004",
          "type": "file",
          "version": "0"
        }
      ],
      "type": "directory",
      "version": "5"
    }
  ],
  "type": "directory",
  "version": "6"
}

### CODE REVIEW

**Comment by EasonLiao** [comment]
@m1ch1 
- change back to previous version - throws exception in validatePath
- Use JsonWriter

**Comment by EasonLiao** [comment]
Add checksum in response.

**Comment by EasonLiao** [comment]
@m1ch1

**Comment by EasonLiao** [comment]
btw, is chunked transfer encoding what we want?

**Comment by ghost** [comment]
i think we can let jetty decide.

**Comment by EasonLiao** [comment]
@m1ch1  can I merge this one?

**Comment by ghost** [comment]
yes. thanks!

**Pull request merged**
