### PR TITLE
creating a new transient directory?

### PR DESCRIPTION
**Pull request by EasonLiao**
I'm not sure if we need to do this. At least I think user should make the request explicit, like : 

```
PUT /foo/bar/file?recursive HTTP/1.1
```

This can avoid typos or the directory has been deleted some other clients they don't know but accidentally recreate them again.

### CODE REVIEW

**Comment by EasonLiao** [comment]
@m1ch1

**Comment by EasonLiao** [comment]
@m1ch1  Now I defined 4 types of nodes : FileNode, DirNode, EphemeralFileNode, TransientDirNode

**Comment by ghost** [comment]
cool, thanks yisheng

**Comment by EasonLiao** [comment]
Fixed the findbug errors.

**Comment by EasonLiao** [comment]
@m1ch1

**Pull request merged**
