### PR TITLE
Create/delete/modify tree nodes

### PR DESCRIPTION
**Pull request by EasonLiao**
@m1ch1  Welcome back!
these pull requests don't contain session feature.
Also now I'm using json for directory as well as file since I feel it's more consistent to do in this way, we can discuss further if you have different opinions.

### CODE REVIEW

**Comment by ghost** [comment]
Cool thanks Yisheng, I'll review the patch tonight.

I do prefer files being blob instead of json. It would be nice to be able to store and retrieve a configuration file without having to parse json for example. It is fairly common for data (file) to be blob and metadata (directory) to be structured, either json or xml:

http://docs.aws.amazon.com/AmazonS3/latest/API/APIRest.html
https://cloud.google.com/storage/docs/json_api/v1/

**Comment by ghost** [comment]
actually google cloud storage has an option to specify whether you want metadata (json) or media (blob). maybe we can do something similar?

http://stackoverflow.com/questions/19630222/how-can-i-download-google-cloud-storage-object-by-metadata-info

**Comment by EasonLiao** [comment]
I'm OK with content just contains the data, and the others are stored in headers. Probably we should support `HEAD` request, this will just reply metadata not data, but I do feel we should make it consistent so if we attach metadata in headers we should always put metadata in headers instead of converting them into json format?

**Comment by EasonLiao** [comment]
I'll let you review this pull request first and fix what we discussed here in other pull requests.

**Comment by ghost** [comment]
the patch looks great overall. i have 2 major comments:
- it's probably better to split file and directory to 2 separate classes with a same parent.
- i guess we are not converting commands to idempotent operations because snapshots are consistent?

as to the file format, let's first come up with a list of metadata for files and directories.

**Comment by EasonLiao** [comment]
we haven't implemented snapshot yet so I think it's not necessary making the transaction idempotent as long as there's no snapshot. Also probably we can get rid of idempotent requirements if the snapshot is consistent.

**Comment by EasonLiao** [comment]
@m1ch1  fixed all.

Now 
- using 19 decimal digits for sequential node
- sort files/directory by name
- get rid of name, only keep fullPath
- separate FileNode and DirNode
- make a separate PathUtils class for path operation

**Pull request merged**
