### PR TITLE
format checksum as a zero-padded hex

### PR DESCRIPTION
**Pull request by EasonLiao**
instead of a decimal number, checksum should be zero-padded hex (e.g. abcd1234).

```
curl localhost:8080
{
  "version": 0,
  "path": "/",
  "sessionID": -1,
  "type": "dir",
  "checksum": "380030",
  "children": []
}
```

### CODE REVIEW

**Comment by ghost** [comment]
it looks like file checksums are formatted as zero-padded hex, but directories aren't

**Comment by ghost** [comment]
sorry it's already in hex, but i guess it's not zero-padded.

**Comment by ghost** [comment]
i guess this needs to be rebased

**Comment by EasonLiao** [comment]
@m1ch1

**Pull request merged**
