### PR TITLE
Implement session feature

### PR DESCRIPTION
**Pull request by EasonLiao**
This is not complete implementation of ephemeral nodes, it's just creation/update of session.

### CODE REVIEW

**Comment by EasonLiao** [comment]
@m1ch1 

You can create and update session like what SPEC suggests, also I add session transfer, which means if you create session on server1 and if you send pulse to server2 then server 2 will take the ownership of the session, this is useful when the owner of session dies so other servers can take the ownership.

Also session files (like /pulsed/sessions/0000xxx) are also ephemeral files, when session dies the session file should also be deleted.

Timeout now is hard coded to 3 seconds, I'll make it configurable in later PR.

I haven't implemented ephemeral node yet, but it should be simple to add, I feel I'd better let you take a look first before I move on.

ADD:

I store the owner of the session in session file like /pulsed/sessions/000xxx, the reason is for simplicity, if we store these in some other data structures then during snapshot we need also snapshot these data structures and also need to take care of consistency stuff. That's why I store them in tree so we'll only take care of the tree during snapshot.

**Comment by ghost** [comment]
great thanks yisheng i'll take a look tonight

**Comment by ghost** [comment]
thanks yisheng the patch looks good except for some minor points.

**Comment by EasonLiao** [comment]
Also add session filter to reject requests with expired sessions.

**Comment by ghost** [comment]
need to be rebased

**Comment by EasonLiao** [comment]
Also added global version, which is pointed in #45

**Comment by EasonLiao** [comment]
@m1ch1

**Pull request merged**
